services:
    prometheus-init:
        image: busybox
        user: root
        volumes:
            - ./prometheus_data:/prometheus/data
        command: chown -R 65534:65534 /prometheus/data

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        # restart: unless-stopped
        user: "65534:65534"  # ✅ run as nobody:nobody
        depends_on:
            prometheus-init:
                condition: service_completed_successfully 
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # relative path
            - ./prometheus_data:/prometheus/data
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.external-url=http://localhost:9090/'
            - '--storage.tsdb.path=/prometheus/data'
        # network_mode: "host"
        # depends_on:
        #     - fastapi-app
        
        # #This manually maps the hostname 'fastapi-app' to the host machine's gateway
        # extra_hosts:
        #     - "fastapi-app:host.docker.internal"

    node_exporter:
        image: prom/node-exporter:latest
        container_name: node_exporter
        restart: unless-stopped
        ports:
            - "9100:9100"
        # # Good for Unix/Mac machines:
        # command:
        #     - '--path.rootfs=/host'
        command:
            - '--path.procfs=/proc'
            - '--path.sysfs=/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        # pid: host
        # volumes:
        #     - /:/host:ro,rslave
        # network_mode: "host"

    # fastapi-app:
    #     build: ./app
    #     container_name: fastapi-app
        # command: python app.py
        # network_mode: "host"
        # ports:
        #     - "5000:5000"

    grafana:
        image: grafana/grafana:latest 
        container_name: grafana
        restart: unless-stopped
        ports:
            - "3000:3000"
        # volumes:
        #     - ./grafana_data:/var/lib/grafana
        # environment:
        #     - GF_SECURITY_ADMIN_PASSWORD=admin
        # depends_on:
        #     - prometheus